### ISSUE TITLE
SlotSet这个对象返回貌似是Set不能做hash

### ISSUE THREAD

**Issue by wangjianhua1** [terrifyzhao/rasa-tutorial#2]
Exception in thread Thread-34:
Traceback (most recent call last):
  File "C:\software\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\software\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\software\Python36\lib\site-packages\rasa_core\channels\channel.py", line 324, in on_message_wrapper
    on_new_message(message)
  File "C:\software\Python36\lib\site-packages\rasa_core\agent.py", line 303, in handle_message
    return processor.handle_message(message)
  File "C:\software\Python36\lib\site-packages\rasa_core\processor.py", line 80, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "C:\software\Python36\lib\site-packages\rasa_core\processor.py", line 306, in _predict_and_execute_next_action
    confidence)
  File "C:\software\Python36\lib\site-packages\rasa_core\processor.py", line 361, in _run_action
    confidence)
  File "C:\software\Python36\lib\site-packages\rasa_core\processor.py", line 430, in _log_action_on_tracker
    tracker.update(e)
  File "C:\software\Python36\lib\site-packages\rasa_core\trackers.py", line 399, in update
    event.apply_to(self)
  File "C:\software\Python36\lib\site-packages\rasa_core\events\__init__.py", line 402, in apply_to
    tracker._set_slot(self.key, self.value)
  File "C:\software\Python36\lib\site-packages\rasa_core\trackers.py", line 492, in _set_slot
    if key in self.slots:
TypeError: unhashable type: 'list'

**Comment by xxllp** [comment]
你这是不是版本哪里有问题

**Comment by wangjianhua1** [comment]
> 你这是不是版本哪里有问题

rasa_nlu==0.14.0
能贴下你的一些版本吗，项目多了，版本也不好管理
